### ISSUE TITLE
Issue with MoveForwardTestSensors2.asm

### ISSUE THREAD

**Issue by jlukose12** [rickyacosta/2031_PROJECT#3]
Check if Sensor Code is working, It seems to end the loop early without any recognition of objects

**Comment by jlukose12** [comment]
Seems to be Jumping to EndStop earlier than it should.

**Comment by rickyacosta** [comment]
I edited ADDI to be 130 instead and it seemed to work. I didn't push the edit though because the value is so far off from what it was before, so maybe something else went wrong? idk
